// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_todo_sample/test/widgets/create_task_modal_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_todo_sample/models/task.dart' as _i2;
import 'package:flutter_todo_sample/repositories/task/i_task_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTask_0 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ITaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITaskRepository extends _i1.Mock implements _i3.ITaskRepository {
  MockITaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Task createTask(String? title) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [title]),
            returnValue: _FakeTask_0(
              this,
              Invocation.method(#createTask, [title]),
            ),
          )
          as _i2.Task);

  @override
  List<_i2.Task> createTasks(List<String>? titles) =>
      (super.noSuchMethod(
            Invocation.method(#createTasks, [titles]),
            returnValue: <_i2.Task>[],
          )
          as List<_i2.Task>);

  @override
  (List<_i2.Task>, bool) fetchTasks({int? page, int? perPage}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTasks, [], {
              #page: page,
              #perPage: perPage,
            }),
            returnValue: (<_i2.Task>[], false),
          )
          as (List<_i2.Task>, bool));
}
